### ISSUE TITLE
Doesn't create a message about restocked items.

### ISSUE THREAD

**Issue by raimharen** [AltaPay/plugin-magento2-community#67] opened 2022-02-02 10:40 UTC
In case of failure like the Back button in the browser and 3DSecureFail (3D Secure 1), Altapay returns items but does not generate a message about them.
![Screenshot from 2022-02-02 12-37-45](https://user-images.githubusercontent.com/69716666/152138320-1e9ac88b-a5e7-4a85-aaef-cec2e33d0667.png)

What should be
![Screenshot from 2022-02-02 12-37-48](https://user-images.githubusercontent.com/69716666/152138423-50eb2068-9435-4bec-831a-d7c21307e109.png)

`Magento - 2.3.6`
`Altapay  - 3.3.0`

**Comment by BushraAsif** [comment] 2022-02-15 08:47
hi @raimharen, the fix will be available on our upcoming release.

**Comment by BushraAsif** [comment] 2022-02-28 10:35
Hi @raimharen, the issue is now fixed in our latest release. Please upgrade the plugin to the 3.3.1 version. 
Thanks

**Closed by BushraAsif** 2022-02-28 10:35 UTC
